DROP TABLE IF EXISTS "user_subscription" CASCADE;
DROP TABLE IF EXISTS "user_bookmark" CASCADE;
DROP TABLE IF EXISTS "user_auth" CASCADE;
DROP TABLE IF EXISTS "article_comment" CASCADE;
DROP TABLE IF EXISTS "article" CASCADE;
DROP TABLE IF EXISTS "user_settings" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;

DROP TYPE IF EXISTS bookmark_type_enum CASCADE;
DROP TYPE IF EXISTS article_status CASCADE;
DROP TYPE IF EXISTS news_line_sort_enum CASCADE;
DROP TYPE IF EXISTS news_line_default_enum CASCADE;
DROP TYPE IF EXISTS user_account_type_enum CASCADE;
